{{- define "common.ingress" -}}
{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "common.name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
{{- toYaml .Values.ingress.annotations | nindent 4 }}
{{- if .Values.ingress.waf.enabled }}
{{- toYaml .Values.ingress.waf.annotations | nindent 4 }}
{{- end }}
{{- if .Values.ingress.additionalAnnotations }}
  {{- tpl .Values.ingress.additionalAnnotations . | nindent 4 }}
{{- end }}
  labels:
{{- include "common.labels" . | nindent 4 }}
spec:
  rules:
{{- if .Values.ingress.host }}
  {{- tpl .Values.ingress.host . | nindent 2 }}
{{- else if .Values.ingress.hostName }}
  - host: {{ .Values.ingress.hostName }}
{{- else }}
  - host: {{ .Values.global.domain }}
{{- end }}
    http:
      paths:
      - backend:
{{- if .Values.ingress.zuul }}
          service:
            name: zuul
            port:
              number: 8080
{{ else }}
          service:
            name: {{ .Values.ingress.serviceName | default (include "common.name" .) }}
            port:
              number: {{ .Values.ingress.servicePort | default .Values.httpPort }}
{{- end }}
        path: /{{ .Values.ingress.context }}
        pathType: Prefix
{{- if ne .Values.global.setup "quickstart" }}
  tls:
{{- if kindIs "map" .Values.ingress.tls }}
  - secretName: {{ .Values.ingress.tls.secretName }}
    hosts:
    {{- range .Values.ingress.tls.hosts }}
      - {{ . }}
    {{- end }}
{{- else if .Values.ingress.hostName }}
  - secretName: {{ .Values.ingress.hostName }}-tls-certs
    hosts:
      - {{ .Values.ingress.hostName }}
{{- else }}
  - secretName: {{ .Values.global.domain }}-tls-certs
    hosts:
      - {{ .Values.global.domain }}
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}
